sudo: required
dist: trusty
language: python
matrix:
    include:
        - python: 3.6
          env: KERAS_BACKEND=tensorflow TEST_MODE=Text
        - python: 3.6
          env: KERAS_BACKEND=tensorflow TEST_MODE=Image
        - python: 3.5
          env: KERAS_BACKEND=tensorflow TEST_MODE=Text
        - python: 3.5
          env: KERAS_BACKEND=tensorflow TEST_MODE=Image
        - python: 3.6
          env: KERAS_BACKEND=theano THEANO_FLAGS=optimizer=fast_compile TEST_MODE=Text
        - python: 3.6
          env: KERAS_BACKEND=theano THEANO_FLAGS=optimizer=fast_compile TEST_MODE=Image
        - python: 3.5
          env: KERAS_BACKEND=theano THEANO_FLAGS=optimizer=fast_comp TEST_MODE=Text
        - python: 3.5
          env: KERAS_BACKEND=theano THEANO_FLAGS=optimizer=fast_comp TEST_MODE=Image
        - python: 3.6
          env: KERAS_BACKEND=cntk PYTHONWARNINGS=ignore TEST_MODE=Text
        - python: 3.6
          env: KERAS_BACKEND=cntk PYTHONWARNINGS=ignore TEST_MODE=Image
install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest pandas
  - source activate test-environment
  - pip install --only-binary=numpy,scipy numpy nose scipy matplotlib h5py theano
  - conda install mkl mkl-service

  # set library path
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH

  # install TensorFlow (CPU version).
  - pip install tensorflow
  - pip install scikit-learn
  - pip  install keras
  
  # install pydot for visualization tests
  - conda install pydot graphviz

# command to run tests
script:
    - if [[ "$TEST_MODE" == "Image" ]]; then
          python Examples/Reuters-21578.py;
        elif [[ "$TEST_MODE" == "Text" ]]; then
          python Examples/MNIST.py;
        fi
